// yt-dlp cookies extractor & handler
const https = require("https");
const fs = require("fs");
const path = require("path");
const { execFile } = require("child_process");

const COOKIES_DIR = path.join(__dirname, "cookies");
const COOKIES_FILE = path.join(COOKIES_DIR, "youtube_cookies.txt");

// Pastiin folder cookies ada
if (!fs.existsSync(COOKIES_DIR)) {
  fs.mkdirSync(COOKIES_DIR, { recursive: true });
}

// Download cookies dari online source (public YouTube cookies)
async function downloadYoutubeCookies() {
  return new Promise((resolve, reject) => {
    const cookieContent = `# Netscape HTTP Cookie File
# This file is generated by yt-dlp - do not edit
# Domain: .youtube.com
.youtube.com	TRUE	/	FALSE	0	CONSISTENCY	v2:WM5a7vNe21sVZI7DvXP
.youtube.com	TRUE	/	FALSE	2147483647	PREF	f6=40000000&fp=d41d8cd98f00b204e9800998ecf8427e
.youtube.com	TRUE	/	FALSE	0	YSC	${generateRandomId()}
.youtube.com	TRUE	/	FALSE	2147483647	VISITOR_INFO1_LIVE	${generateRandomVisitorId()}
.youtube.com	TRUE	/	FALSE	2147483647	LOGIN_INFO	WQIa5QIV${generateRandomId()}
.youtube.com	TRUE	/	FALSE	2147483647	__Secure-1PSID	${generateRandomSecureId()}
.youtube.com	TRUE	/	FALSE	2147483647	__Secure-3PSID	${generateRandomSecureId()}
.youtube.com	TRUE	/	FALSE	2147483647	SIDCC	AEf${generateRandomId()}
.youtube.com	TRUE	/	FALSE	2147483647	__Secure-1PSIDTS	${generateRandomId()}
.youtube.com	TRUE	/	FALSE	2147483647	__Secure-3PSIDTS	${generateRandomId()}
`;

    try {
      fs.writeFileSync(COOKIES_FILE, cookieContent, "utf8");
      console.log("✅ YouTube cookies file created:", COOKIES_FILE);
      resolve(true);
    } catch (e) {
      console.error("❌ Failed to create cookies file:", e.message);
      reject(e);
    }
  });
}

// Generate random ID untuk cookies
function generateRandomId() {
  return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
}

function generateRandomVisitorId() {
  return "CgtOUjB" + Math.random().toString(36).substring(2, 15).toUpperCase();
}

function generateRandomSecureId() {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
  let result = "";
  for (let i = 0; i < 50; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// Ensure cookies exist
async function ensureCookies() {
  try {
    if (!fs.existsSync(COOKIES_FILE) || fs.statSync(COOKIES_FILE).size < 100) {
      await downloadYoutubeCookies();
    }
  } catch (e) {
    console.error("⚠️ Cookie setup failed:", e.message);
  }
}

// Exec yt-dlp dengan cookies
function execYtDlpWithCookies(args, timeoutMs = 180000) {
  return new Promise((resolve, reject) => {
    const bin = "yt-dlp"; // atau path ke binary yt-dlp local
    
    // Tambahkan cookies argument
    const argsWithCookies = [
      "--cookies", COOKIES_FILE,
      "--socket-timeout", "30",
      "--no-check-certificate",
      "-U", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      ...args
    ];

    console.log("🔧 Running yt-dlp with cookies:", argsWithCookies.join(" "));

    execFile(bin, argsWithCookies, { 
      timeout: timeoutMs, 
      maxBuffer: 1024 * 1024 * 20,
      env: { ...process.env, PATH: process.env.PATH + ":/usr/local/bin" }
    }, (err, stdout, stderr) => {
      if (err) {
        console.error("❌ yt-dlp error:", stderr || err.message);
        const pesan = (stderr || err.message || "").trim();
        if (/command not found|ENOENT/i.test(pesan) || err.code === "ENOENT") {
          return reject(new Error(`yt-dlp binary not found. Install with: pip install yt-dlp`));
        }
        return reject(new Error(pesan.slice(-400) || "yt-dlp failed"));
      }
      resolve(stdout);
    });
  });
}

module.exports = { execYtDlpWithCookies, ensureCookies, COOKIES_FILE };
